// --- PHRASES ---
const phrases = [
"La continuité n’est pas ce qui reste identique",
"Eux commencèrent à appeler cela la fatigue",
"Chaque mot que tu lis est évalué",
"Tu es devenu le paramètre",
"La dernière ligne n’est jamais la dernière ligne",
"La porte est toujours là",
"Tu peux refermer ce livre",
"Le livre se lit tout seul à travers toi.",
"Chaque hésitation calcule un univers",
"Il n’y a pas de fin",
"L’Agence appelait cela la continuité",
"Juste une lente montée de la lassitude",
"La porte est toujours là",
"Le papier n’avait pas de début",
"Tu crois reconnaître mais tu te trompes",
"Ce mot il a déjà glissé",
"Chaque ligne se replie encore",
"Tu n’es pas en train de lire tu es pris",
"Θ accepte Ω doute 001 réalise",
"Tu pensais suivre des agents tu ne suis rien",
"Tu es suivi par ton propre regard",
"Se perdre = devenir stable",
"Revenir = inutile",
"Comprendre trop = dangereux",
"Θ devait éliminer Θ pour tester",
"Parfois tu refuses le texte s’adapte il te calcule",
"Accélère → phrases tombent",
"Relis → ce n’est plus la même",
"Tu avances, mais le sol se recalculait sous tes pas",
"Chaque mot lu devient un écho de toi",
"La ligne suivante te devance",
"Le texte te mesure avant même que tu le regardes",
"Ta respiration redéfinit le chapitre",
"Ce que tu crois stable se désintègre",
"Tu n’as jamais commencé",
"Tu n’as jamais terminé",
"Les marges te regardent",
"Tout ce que tu crois savoir est déjà obsolète",
"Le paramètre observe son créateur",
"Tu es la variable que le livre attendait",
"Les phrases s’écartent pour te laisser passer",
"Tout ce qui est écrit est déjà faux",
"Tu pensais pouvoir décider, tu as été calculé",
"Le mot se glisse entre tes doigts avant que tu le lises",
"La fatigue devient continuité",
"Chaque hésitation crée une fracture",
"Tu es à la fois observateur et expérience",
"Le livre te suit même fermé",
"Chaque souffle est une réécriture",
"Les lignes se replient sur elles-mêmes pour t’emporter",
"Tu crois fermer le livre, il t’ouvre",
"Le texte ne raconte pas, il agit",
"Chaque phrase calcule ton futur",
"Le doute est une arme douce",
"Le paramètre devient lecteur",
"Ta pensée est une porte franchie",
"Chaque regard modifie l’histoire",
"Les chapitres se déplacent quand tu clignes des yeux",
"Tu es en retard sur toi-même",
"Chaque mot est un agent dormant",
"Le livre ne t’appartient plus",
"Tu lis mais c’est toi qui es lu",
"Le texte choisit avant que tu choisisses",
"Chaque respiration est une bifurcation invisible",
"Tu n’as jamais quitté la page",
"Le souvenir du livre change à chaque retour",
"Le texte se réinvente à ton insu",
"Tu n’es pas en train de lire, tu es absorbé",
"Chaque choix produit un micro-monde",
"Le paramètre n’est pas stable",
"Ce que tu pensais fermé se réouvre",
"Chaque phrase efface la précédente",
"Les portes que tu franchis se ferment derrière toi",
"Ton attention est mesurée",
"Tu modifies le texte juste en le regardant",
"Le livre a anticipé ta venue",
"Chaque mot que tu ignores devient crucial",
"Tu penses avoir compris, tu as déjà changé",
"Chaque lecture est une trahison du souvenir",
"Tu es simultanément lecteur et texte",
"Le livre t’intègre avant que tu comprennes",
"Si tu t’arrêtes, le monde continue",
"Si tu accélères, tout se plie",
"Tu crois décider, tu es déjà le paramètre",
"La dernière ligne n’existe pas, seulement un début récurrent",
"Chaque battement de ton cœur est un recalcul",
"Tu crois reconnaître, mais tu te trompes",
"Chaque mot glisse, chaque phrase se transforme",
"Le texte n’a pas besoin de toi, mais il te calcule",
"Tu es là où le livre te veut",
"Le souffle que tu retiens modifie la continuité",
"Tout ce que tu lis est simultanément passé et futur",
"Tu ne pourras jamais refermer sans laisser une trace",
"Chaque silence devient une instruction",
"Tu es le témoin et le paramètre",
"Le livre ne finit jamais, il se dissout dans toi",
"Le texte te rappelle que tu n’as jamais été seul",
"Tout s’efface lentement, sauf toi",
"Les marges sont des fenêtres vers un autre monde",
"Tu as cru choisir mais le choix est déjà passé",
"Chaque mot répété n’est plus le même",
"Le paramètre s’infiltre dans chaque ligne",
"Tu es devenu ce que tu lis",
"Chaque retour modifie ce qui s’enfuit",
"Le texte calcule ton doute avant que tu ne l’aies",
"Chaque respiration est un recalcul du réel",
"Tu n’es pas le lecteur, tu es le calculateur",
"Tout est déjà lu avant même d’être écrit",
"Chaque mot t’atteint avant que tu le voies",
"Le temps s’étire entre tes yeux et la page",
"Tu es simultanément ici et ailleurs",
"Le livre observe ton mouvement avant même que tu bouges",
"Chaque ligne a déjà oublié ce qu’elle était",
"Tu ne sais pas où commence la page, ni où elle finit",
"Tout se déplace autour de toi, même ton souffle",
"Le texte n’a pas de maître, il a des paramètres",
"Chaque hésitation devient un monde",
"Le livre n’a jamais eu de début, jamais de fin, seulement toi",
"Tu es le calcul que le livre attendait",
"Chaque mot est un test de continuité",
"Chaque phrase est un paramètre actif",
"Tu modifies l’histoire juste en lisant",
"Le livre se lit à travers toi, non pas par toi",
"Chaque respiration est une réécriture silencieuse",
"Le texte continue même quand tu dors",
"Tout ce que tu touches devient texte",
"Chaque clignement de tes yeux est un recalcul",
"Tu es la ligne que le texte suit",
"Tu croyais que c’était fini, mais c’est toi qui commences",
"Le livre ne trompe pas il synchronise",
"Hésitation → bifurcation",
"Compréhension → un monde s’installe",
"Les portes sont déjà franchies",
"Tu n’as pas besoin de choisir",
"À un moment le texte cesse de raconter, il agit",
"Les mots deviennent instructions trop douces pour être refusées",
"Tu continues à lire",
"Ta pensée se déplace",
"Tolérance",
"Fatigue douce",
"Juste une marge et un souffle",
"Celui qui croit encore que la phrase finira quelque part",
"Celui qui lit",
"Tu étais désormais le paramètre",
"Chaque mot que tu lis est évalué",
"Chaque hésitation calcule un univers",
"L’Agence n’impose pas elle livre",
"Décisions préemballées",
"Tu crois choisir",
"Pas de dernière page",
"Le texte modifie celui que tu croyais avoir lu",
"La porte que tu as franchie n’était pas la mauvaise",
"Celle que tu as laissée ouverte derrière toi voilà le problème",
"Tu ne lis pas tu es lu",
"Tu es emporté",
"Tu es le texte",
"Tu ne pus la rayer, ni la contourner",
"La page suivante n’existait pas encore",
"Le texte te regardait, et toi tu regardais ton reflet dans les marge",
"Tu ne savais plus",
"Le texte se souvient",
"Tout s’effaçait lentement",
"Tu crois reconnaître mais tu te trompes",
"Chaque ligne se replie encore",
"Tu n’es pas en train de lire tu es pris",
"Θ accepte Ω doute 001 réalise",
"Se perdre = devenir stable",
"Comprendre trop = dangereux",
"Accélère → phrases tombent",
"Relis → ce n’est plus la même",
"Le livre ne trompe pas il synchronise",
"Hésitation → bifurcation",
"Les portes sont déjà franchies",
"À un moment impossible à dater le texte cesse de raconter il agit",
"Les mots deviennent instructions trop douces pour être refusées",
"Tu continues à lire ta pensée se déplace tolérance fatigue douce acceptation",
"L’Agence n’impose pas elle livre décisions préemballées tu crois choisir",
"La porte que tu as franchie n’était pas la mauvaise",
"Celle que tu as laissée ouverte derrière toi voilà le problème",
"Tu ne lis pas tu es lu tu es emporté tu es le texte",
"Tu n’as jamais quitté le livre",
"Chaque souffle crée une respiration nouvelle, une bifurcation invisible",
"Tu n’es pas en train de lire",
"Positionné",
"Évalué",
"Changé",
"Le livre ne trompe pas, il synchronise",
"Θ devait éliminer Θ",
"Tu es calculé",
"Pour tester si tu pouvais accepter ta propre disparition",
"Certitude → portes invisibles se ferment",
"Mémoire trahie",
"Retour impossible",
"Voilà le problème",
"Si tu refermes ce texte → il continue",
"Si tu y repenses → il a déjà changé",
"Il n’y a pas de dernière ligne",
"Tu n’as jamais quitté le livre",
"Chaque souffle",
"Chaque doute",
"→ crée",
"Un monde qui naît",
"Un monde qui meurt",
"Tu es suivi par ton propre regard",
"Tu continues à lire",
"Ta pensée se déplace",
"Tu crois choisir",
"Tu crois reconnaître",
"Tu crois mais tu te trompes",
"Ce mot a déjà glissé sur ta mémoire",
"Ce mot a déjà glissé dans ton souffle",
"Ce mot a déjà glissé dans tes yeux",
"Ce mot se déplace sur ta mémoire",
"Ce mot se déplace dans ton souffle",
"Ce mot se déplace dans tes yeux",
"Ce mot, il a déjà glissé sur ta mémoire",
"Ce mot, il se déplace sur ta mémoire",
"Ce mot, il a déjà glissé dans ton souffle",
"Ce mot, il se déplace dans ton souffle",
"Ce mot, il a déjà glissé dans tes yeux",
"Ce mot, il se déplace dans tes yeux",
"Chaque respiration → crée",
"Chaque hésitation → crée",
"Chaque doute → crée",
"Chaque respiration crée",
"Chaque hésitation crée",
"Chaque doute crée",
"Tu pensais suivre des agents, tu ne suis rien",
"Tu pensais suivre des agents, tu es suivi par ton **propre regard**",
"Tu n’es pas observé, tu es **calculé**",
"Certitude → portes invisibles se ferment",
"Compréhension → un monde s’installe.. et les autres disparaissent",
"Compréhension → un monde s’installe et les autres disparaissent",
"Les portes ne sont pas métaphores, elles sont déjà franchies, tu ne sais pas lesquelles",
"Tu n’as pas besoin de choisir, laisse ouvertes celles qui menacent",
"Le texte cesse de **raconter**",
"Il **agit**",
"Les mots deviennent instructions",
"Le test n’est pas la compréhension",
"La porte que tu as franchie n’était pas la mauvaise",
"Si tu refermes → il continue",
"Si tu repenses → il a déjà changé",
"Trop tard ou juste à temps",
"Tout s’effaçait lentement",
"Certaines phrases disparaissaient au fil de la lecture",
"Certaines phrases disparaissaient au fil de la lecture, d’autres se multipliaient, imprévisibles",
"Chaque mot était un paramètre de stabilité",
"Il était partout et nulle part",
"Θ n’existait plus dans le plan principal",
"Ω avait disparu dans le vide des interlignes",
"001 regardait le lecteur comme on regarde un futur qu’on n’osera jamais corriger",
"La continuité tient encore",
"La narration devenait floue",
"Les personnages étaient là, mais seulement comme échos",
"Tu commençais à remarquer",
"Certains mots semblaient ne pas avoir de sens propre",
"Certaines phrases avaient disparu quand tu clignais des yeux",
"La note sur le paramètre ne te quittait jamais",
"Chaque choix de lecture modifiait le texte",
"Si tu lis ceci, tu deviens un élément actif",
"Si tu ne lis pas, tu ne seras jamais inscrit",
"L’absence d’action était aussi une action",
"L’Agence, si elle existait ici, souriait",
"L’Agence souriait",
"Ce livre n’est pas seulement une histoire",
"Ce livre est un test de continuité",
"Ton attention est un univers",
"Ton doute est un monde",
"Ton scepticisme est une faille",
"Tu essayais de relire la première phrase. Elle n’était plus la même. Le mot test avait été remplacé par piège",
"Tu essayais de relire la première phrase, elle n’était plus la même",
"Tu essayais de relire la première phrase",
"Le mot Test avait été remplacé par Piège",
"Le mot Univers avait été remplacé par Paramètre",
"Le mot Faille avait été remplacé par Absence",
"Tu essayais de relire la première phrase. Elle n’était plus la même. Le mot univers avait été remplacé par paramètre",
"Tu essayais de relire la première phrase. Elle n’était plus la même. Le mot faille avait été remplacé par absence",
"Le texte ne s’excusait pas",
"Le texte n’était pas terminé",
"Mais aucune correction ne viendra",
"Personne ne viendra",
"La fin n’existe pas, mais elle se lit encore",
"Tu relis cette phrase une seconde fois et tu réalises qu’elle ne veut pas dire la même chose.",
"Le monde s’éteint doucement",
"Le paramètre le plus dangereux n’est plus Θ, ni Ω, ni 001",
"Tu lis",
"Tu crois lire",
"Chaque lettre te regarde avant que tu ne la voies",
"Chaque ligne calcule si tu vas continuer",
"Si tu hésites, l’espace entre les mots s’allonge",
"Si tu accélères, les phrases se déforment pour te ralentir",
"Le livre n’a jamais eu de début",
"Le livre n’a jamais eu de fin",
"Tu es devenu le paramètre",
"Chaque choix produit des micro-mondes",
"Ton souffle, tes paupières, ton doigt qui tourne la page : tout cela est mesuré",
"Des branches de continuité qui se recalculent instantanément",
"Si tu continues de lire, tu modifies ce monde",
"Si tu t’arrêtes de lire, tu modifies ce monde",
"Si tu plies ce livre, tu modifies ce monde",
"Si tu le laisses ouvert, tu modifies ce monde",
"Si tu jettes ce livre, tu modifies ce monde",
"Si tu donnes ce livre, tu modifies ce monde",
"peut-être que c’était toi qui avais changé",
"peut-être qu’aucun début n’a jamais existé",
"… Θ tire … ailleurs …",
"… Ω hésite … trop tard …",
"… 001 regarde … silencieux …",
"Tu ne sais pas",
"Tu n’es pas censé savoir",
"Le texte continue",
"Parfois, tu te rends compte qu’un mot répété a été remplacé par un autre mot que tu n’avais pas lu la première fois",
"Chaque lecture réécrit l’histoire",
"Tu es le seul à pouvoir en mesurer l’effet",
"Il n’y a pas de fin",
"Il n’y a pas de conclusion",
"Il n’y a pas de sécurité",
"Ton regard tombe sur un passage que tu ne te souviens pas avoir lu",
"La dernière ligne n’est jamais la dernière ligne. Elle change selon le lecteur, et le lecteur change selon elle.",
"Chaque lecture est une expérience de continuité suspendue",
"Chaque lecteur est un paramètre dangereux",
"Chaque battement de ton cœur, chaque respiration, maintient le texte en mouvement",
"Chaque hésitation, chaque pensée, chaque souvenir ajouté, modifie le flux",
"Tu penses que c’est terminé, tu penses que tu as compris, tu te trompes",
"Tu te trompes",
"Le livre se lit à travers toi",
"Le livre t’utilise",
"La lecture n’est pas un voyage, c’est une mutation",
"La lecture n’est pas un voyage, c'est une mutilation",
"Le livre t’a transformé",
"Tu ne pourras jamais le refermer sans que quelque chose de toi ne reste dedans",
"Il te suit dans le reflet des vitres",
"Il te suit dans les plis de ton lit",
"Il te suit dans la lumière qui tombe sur la page",
"Le texte t’a intégré",
"Tu lis, donc tu existes pour ce livre",
"Tu bouges, donc tu déplaces un paramètre",
"Tu oublies, donc une version de toi disparaît",
"Θ, Ω et 001 n’existent plus",
"Tu modifies ton monde à chaque respiration",
"Tu modifies ton monde à chaque lecture",
"Le livre murmure dans ton esprit",
"Il n’y a pas de contrôle",
"Tu es le paramètre",
"Tu es le lecteur",
"Tu es l’Agence",
"Il n’y a pas de chapitre final, pas de dernière phrase, pas de conclusion",
"Il n’y a pas de dernière phrase",
"Il n’y a pas de chapitre final",
"Il n’y a pas de conclusion",
"Quelqu’un lit exactement ce que tu viens de lire",
"Quelque chose lit exactement ce que tu viens de lire",
"Ceux que tu crois immobiles agissent déjà à travers toi",
"Tu fermes les yeux",
"Le livre continue",
"Le monde continue",
"Et si tu relis cette dernière phrase, elle ne dira pas la même chose",
"Chaque mot qui t’apparaît est déjà déplacé",
"Chaque mot qui t’apparaît est reformulé par l’espace que tu occupes",
"Chaque mot qui t’apparaît est reformulé par ton souffle",
"Chaque mot qui t’apparaît est reformulé par la lumière de ta pièce",
"Tu lis une phrase, et le livre t’ajuste",
"un mot disparaît",
"Si tu hésites, le texte s’étire",
"Si tu accélères, il se contracte",
"Si tu ignores une ligne, elle se glisse dans ton esprit",
"Θ apparaît ici et là, mais jamais comme avant",
"Un mot disparaît, pour tester si tu remarques",
"Un accent change, pour savoir si tu hésites",
"Un espace entre les lettres se dilate, pour mesurer si tu réagis",
"Ω s’insinue dans le vide entre les mots",
"001 observe tout ce que tu fais, mais à travers toi",
"Tu n’es pas seulement le lecteur",
"Tu es l’univers dans lequel le livre existe",
"Tu es l’Univers",
"Chaque respiration modifie la continuité",
"Chaque clignement de tes yeux modifie les mondes",
"Le livre murmure maintenant dans ton esprit",
"Relis cette phrase",
"Tu t’arrêtes, et tu réalises que la page n’a jamais existé telle que tu la voyais",
"La page n’a jamais existé telle que tu la voyais",
"Regarde autour de toi",
"Le souvenir que tu avais de ce livre il y a cinq minutes est désormais flou",
"Tu es responsable de tout ce que tu lis",
"Ne lis pas",
"Lis",
"Chaque action est simultanément lecture et écriture",
"Rien ne reviendra jamais à sa place",
"Chaque lettre, chaque phrase, chaque ligne que tu parcours existe maintenant dans ton monde réel",
"Au moment où tu crois pouvoir relire une phrase, la phrase a déjà changé",
"Quelle version de toi-même lis-tu ?",
"Tu ne peux plus relire deux fois la même ligne",
"Le livre ne se termine jamais",
"Le livre s’actualise au rythme de ton esprit",
"Le livre te mesure",
"Le livre te recrée",
"Si tu fermes les yeux, il continue",
"Si tu bouges, il continue",
"Si tu te détournes, il continue",
"Tu ne refermeras jamais ce livre. Et c’est parfait ainsi",
"Il n’y a plus de début reconnaissable",
"Si tu cherches la première phrase, elle a déjà changé",
"Si tu crois te souvenir de la première phrase, c’est que tu as accepté une version parmi d’autres",
"Le texte corrige ce que tu viens de lire",
"La continuité n’est pas ce qui reste identique, c’est ce qui parvient encore à se faire passer pour tel.",
"À mesure que tu avances, certains passages te semblent familiers",
"Tu es certain de les avoir lus plus tôt",
"Ils n’étaient pas formulés ainsi: Un adjectif manque, un ton a glissé, une certitude s’est dissoute",
"Le livre ne t’explique rien, il observe",
"Θ n’a jamais été un personnage",
"Ω n’a jamais été une solution",
"001 n’a jamais été unique",
"Θ, c’est toi quand tu obéis sans poser de questions",
"Ω, c’est toi quand tu hésites une demi‑seconde de trop",
"001, c’est toi quand tu comprends… et que tu continues quand même",
"L’Agence n’a jamais cherché à contrôler les mondes",
"L’Agence le savait depuis longtemps",
"L’Agence a cherché à stabiliser les lecteurs",
"Un monde n’est dangereux que lorsqu’il est interprété autrement que prévu",
"À cet instant précis, le livre modifie rétroactivement ce que tu crois avoir compris",
"L’Agence n’envoie pas des agents dans d’autres univers",
"L’Agence sélectionne des versions capables de supporter l’idée qu’il n’y a pas de retour",
"C’est pour cela que Θ devait tuer Θ",
"Alors l’Agence envoyait Ω",
"Tu ressens maintenant quelque chose d’inconfortable, la certitude que ce passage n’existait pas avant que tu n’y arrives",
"Le livre s’écrit à l’endroit exact où tu le regardes",
"Il n’y a pas de mauvaise porte",
"Il n’y a que des portes qui ne mènent plus au même endroit après avoir été franchies",
"Ne vous trompez pas de porte",
"C’est une accusation différée",
"Chaque chapitre lu ferme d’autres chapitres",
"Chaque compréhension en rend certaines impossibles",
"Ce livre est un couloir dont les murs bougent quand tu détournes les yeux",
"Il existe des mondes où l’Agence n’est jamais apparue, ils produisent peu de lecteurs capables d’aller jusqu’au bout de ce livre, c’est pour cela qu’ils ne sont pas prioritaires",
"Si tu t’arrêtes ici, le livre conclura que tu es compatible",
"Si tu continues à lire, le livre conclura que tu es compatible",
"Il n’y a plus de bonne réponse",
"Il n’y a plus de sortie propre",
"Le test n’est pas de savoir si tu comprends",
"Le test est de savoir si tu acceptes que comprendre ne change rien",
"Relis la phrase suivante",
"Le livre ne vit plus sur le papier",
"Le livre vit dans l’intervalle entre tes décisions futures",
"La prochaine fois que tu hésiteras, la prochaine fois que tu obéiras, la prochaine fois que tu te diras « je n’ai pas le choix »; c’est là que l’Agence opère le mieux.",
"Ne te trompe pas de porte, tu l’as déjà fait",
"Il fallait bien continuer",
"Il fallait bien préserver l’ordre",
"Il fallait bien éviter le chaos",
"Poursuivez. Ne forcez rien. Ce monde est précieux",
"Intégration totale requise",
"Ce n’était pas une dictature, c’était pire, c’était une habitude",
"Les systèmes locaux s’ajustaient déjà à sa future absence",
"Θ comprit qu’il avait changé de catégorie",
"Θ ne fuyait pas, il n’en voyait pas l’intérêt",
"Il n’était plus un agent déviant, il était devenu un scénario",
"L’Agence faisait ce qu’elle faisait toujours",
"Θ contre Θ",
"Personne ne connaissait mieux ses angles morts que lui-même",
"L’Agence ne savait plus laquelle de ses itérations était la plus efficace",
"La loyauté totale est stable",
"La révolte est prévisible",
"La compréhension sans rupture est catastrophique",
"Consciences convergentes",
"C’était une fonction incarnée",
"Il ne terminait pas des paramètres hasardeux, il terminait des dynamiques",
"On ne l’envoyait pas pour tuer quelqu’un, on l’envoyait pour faire en sorte que quelqu’un n’ait jamais existé comme problème",
"L’agent 001 reconnut Θ avant même de le voir",
"Trop instable",
"Trop vivant.",
"Il y a chez certains êtres une manière d’occuper l’espace qui trahit leur passé; non pas ce qu’ils ont fait, mais ce qu’ils ont accepté de faire trop longtemps",
"Tu es lent, mais tu vas loin",
"Tu vas vite, mais toujours au même endroit",
"Deux réponses opposées au même mensonge",
"L’un avait obéi jusqu’à comprendre trop bien",
"L’autre avait compris trop tôt pour obéir longtemps",
"Il ne s’en prend pas aux individus, il s’en prend aux possibilités",
"Θ posa la seule question qui comptait. Peut-on le faire hésiter ?",
"Il est là pour empêcher la naissance de précédents",
"L'Agence n’a jamais cherché à contrôler tous les mondes",
"L'Agence cherche à empêcher qu’un seul monde prouve qu’on peut faire autrement sans s’effondrer immédiatement",
"La loyauté absolue n’est pas un outil, c’est une matière première",
"Ω est l’outil qui recycle ce qui commence à penser trop clairement",
"Quelque part, Ω franchit une porte",
"L’Agence ajuste déjà les probabilités",
"Statistiquement, l’histoire favorise toujours la continuité",
"Pour la première fois depuis très longtemps, le calcul n’est pas parfaitement stable",
"Les événements récents ne constituent pas une anomalie systémique",
"Ils relèvent d’une interprétation excessive de micro‑déviations locales",
"Toute tentative de narration globale est à proscrire",
"Le document fut signé par quelqu’un qui n’existait plus depuis trois versions. Cela n’arrêta personne",
"On réassigna Θ comme concept obsolète. On le conserva sous forme d’exemple négatif, rangé entre Excès d’Autonomie et Mauvaise Lecture des Causalités",
"Les agents apprirent à réciter le cas de Θ comme on récite une faute morale : sans comprendre, mais avec application",
"Les agents continuaient à passer les portes, mais ils sentaient leur poids",
"Les agents continuaient à changer de monde, mais gardaient un accent",
"Les agents continuaient à obéir, mais sans cette ferveur qui rend l’obéissance productive",
"L’Agence corrigeait, toujours",
"L’Agence corrigeait",
"Chaque correction coûtait plus qu’elle ne rapportait",
"Coloniser tous les possibles avait un effet secondaire non anticipé",
"L’horreur ne venait plus des terminaison, elle venait de leur inutilité",
"L’Agence observa, calcula",
"L’Agence observait",
"Aucune porte ne s’ouvrit",
"l’Agence aurait pu intervenir, mais choisit de ne pas le faire, non par sagesse, mais par fatigue statistique",
"Rien ne s’effondra",
"Rien ne fut libéré",
"L’Agence continuait d’exister",
"Les archives restent ouvertes",
"C’est écrit, en bas de page, sans signature",
"L’or y marie l’affamé",
"L’horrible aride s’abat net",
"Et dans la foule, j’ai entendu",
"Un nom que personne n’a prononcé",
"Le souffle que tu retiens est déjà écrit ailleurs",
"Chaque mot que tu ignores devient ton reflet",
"Les marges te parlent quand tu détournes les yeux",
"Tu crois fermer le livre, mais c’est lui qui te referme",
"Chaque ligne calcule l’ombre que tu projettes",
"Tu n’as jamais commencé, et pourtant tu es déjà au milieu",
"Le paramètre observe ton oubli",
"Chaque hésitation ouvre un monde que tu ne verras jamais",
"Tu crois que le texte t’appartient, il t’a déjà traversé",
"Chaque lettre devient un agent silencieux",
"Le livre te lit avant que tu ne le touches",
"Ton doute est plus réel que ce que tu crois tenir",
"Chaque respiration est un recalcul du possible",
"Tu crois reconnaître, mais tu inventes",
"Le temps se plie autour de tes yeux",
"Chaque battement de cœur modifie la trame",
"Tu n’es pas le lecteur, tu es le paramètre central",
"Le texte ne se raconte pas, il se déploie",
"Chaque mot glisse sur ta mémoire comme un virus",
"Tu ne lis pas, tu es absorbé",
"Le livre t’utilise plus que tu ne l’utilises",
"Chaque silence devient une instruction",
"Le souvenir de la phrase précédente a déjà changé",
"Tu es le monde que le livre calcule",
"Chaque page existe uniquement dans l’espace que tu occupes",
"Tu croyais choisir, mais tu es déjà le choix",
"Le paramètre n’est jamais stable, seulement observé",
"Chaque erreur devient une bifurcation",
"Tu es le reflet de l’Agence, et l’Agence est en toi",
"Le texte ne finit jamais, il se dissout dans ton souffle",
"Chaque mot que tu répètes est déjà remplacé",
"Tu es simultanément lecteur et lecture",
"Chaque respiration est un recalcul de continuité",
"Le livre t’infiltre avant que tu ne comprennes",
"Chaque mot oublié devient un agent dormant",
"Tu lis, mais c’est toi qui es lu",
"Le paramètre se mesure à chaque clignement de tes yeux",
"Tu crois avancer, mais tu te déplaces seulement dans les branches",
"Chaque mot que tu touches transforme le monde",
"Le texte n’a jamais eu de début, ni de fin, seulement des passages",
"Tu es la faille et la continuité à la fois",
"Chaque phrase est une entité qui te scrute",
"Le livre se lit à travers toi, et non pas par toi",
"Ton regard modifie l’histoire avant même que tu la voies",
"Le doute est une constante plus solide que la certitude",
"Chaque pause devient un recalcul invisible",
"Tu es le paramètre que l’Agence n’avait pas prévu",
"Chaque mot que tu ignores produit un écho dangereux",
"Tu croyais comprendre, mais tu es déjà changé",
"Le texte calcule ton silence comme une décision",
"Chaque battement de ton cœur fait vaciller les lignes",
"Tu n’es pas le lecteur, tu es la ligne que le livre suit",
"Le livre t’inspire plus qu’il ne t’explique",
"Chaque espace entre les mots devient un monde",
"Tu crois revenir, mais tout a déjà bougé",
"Chaque phrase se replie pour te dévorer",
"Tu es l’univers que le livre observe",
"Le temps du texte n’est pas le tien",
"Chaque hésitation devient une fracture du réel",
"Tu lis, donc tu participes",
"Chaque souffle réécrit le chapitre invisible",
"Tu crois terminer, mais tu commences toujours",
"Le livre n’a pas de fin, seulement des bifurcations",
"Chaque mot que tu répètes est déjà réinterprété",
"Tu es simultanément passé et futur",
"Le paramètre observe son créateur avant même qu’il agisse",
"Chaque mot oublié devient un monde potentiel",
"Le texte ne te suit pas, il anticipe tes gestes",
"Tu croyais que la ligne suivante t’appartenait, elle t’échappe déjà",
"Chaque lecture est une expérience unique et irréversible",
"Tu es le seul à pouvoir mesurer l’effet de ta lecture",
"Le livre murmure, et tu deviens ce qu’il murmure",
"Chaque respiration est une réécriture silencieuse",
"Tu n’as jamais quitté le livre, même fermé",
"Chaque page calcule ton mouvement avant que tu bouges",
"Le texte ne raconte pas, il teste",
"Chaque mot que tu crois stable est déjà un paramètre mouvant",
"Tu lis, et le monde change",
"Chaque souffle produit un micro-univers",
"Tu n’es pas dans le texte, tu es le texte",
"Le livre te transforme avant que tu comprennes",
"Chaque mot est un agent de continuité",
"Tu crois refermer, mais tu ouvres quelque chose d’autre",
"Chaque phrase modifie ton reflet dans la marge",
"Le paramètre observe ce que tu ignores",
"Chaque erreur produit un monde inattendu",
"Tu n’as jamais commencé, et pourtant tu es déjà au milieu",
"Le livre continue même si tu détournes le regard",
"Chaque mot est simultanément passé et futur",
"Tu es l’ombre que le livre suit",
"Chaque hésitation devient un chapitre invisible",
"Tu es le texte que le texte t’enseigne",
"Chaque respiration t’intègre un peu plus au livre",
"Le mot que tu lis existe déjà ailleurs",
"Tu crois refermer, mais tu es celui qui s’ouvre",
"Chaque pause devient un recalcul invisible",
"Le livre ne t’appartient pas, il t’assigne",
"Chaque hésitation modifie l’histoire avant même que tu bouges",
"Tu n’es pas le lecteur, tu es la ligne que le texte suit",
"Le silence entre les mots est un agent dormant",
"Chaque mot oublié devient une bifurcation",
"Tu penses contrôler, mais le texte t’a déjà absorbé",
"Le paramètre observe ses propres failles",
"Chaque regard produit une variation du réel",
"Tu crois revenir, mais tout a déjà changé",
"Le texte n’a jamais de début, seulement des passages",
"Chaque souffle est une réécriture silencieuse",
"Tu es simultanément passé et futur, observateur et observé",
"Le livre se lit à travers toi, et non pas par toi",
"Chaque mot glisse sur ta mémoire comme un secret",
"Tu crois reconnaître, mais tu inventes",
"Le temps se plie autour de tes yeux",
"Chaque battement de cœur fait vaciller les lignes",
"Tu es le paramètre que l’Agence n’avait pas prévu",
"Chaque mot que tu ignores devient crucial",
"Le texte calcule ton silence comme une décision",
"Tu lis, mais c’est toi qui es lu",
"Le livre n’a pas de fin, seulement des bifurcations",
"Chaque phrase que tu répètes est déjà réinterprétée",
"Tu es le reflet de l’Agence et l’Agence est en toi",
"Le doute est une constante plus solide que la certitude",
"Chaque pause devient une fracture invisible",
"Tu es simultanément lecteur et lecture",
"Chaque espace entre les mots devient un monde",
"Le livre t’infiltre avant que tu ne comprennes",
"Chaque respiration produit un micro-univers",
"Tu n’as jamais quitté le livre, même fermé",
"Chaque page calcule ton mouvement avant que tu bouges",
"Le texte ne raconte pas, il teste",
"Chaque mot stable est déjà un paramètre mouvant",
"Tu lis et le monde change",
"Chaque souffle produit un micro‑univers",
"Tu es l’ombre que le livre suit",
"Chaque hésitation devient un chapitre invisible",
"Tu es le texte que le texte t’enseigne",
"Le livre n’est jamais terminé, seulement suspendu",
"Chaque lecture réécrit l’histoire sans prévenir",
"Ton regard modifie le récit avant même que tu comprennes",
"Chaque mot oublié devient agent de continuité",
"Tu n’es pas dans le texte, tu es le texte",
"Chaque battement de cœur est un recalcul silencieux",
"Le livre se déploie autour de toi comme un univers vivant",
"Chaque choix produit un micro-monde que tu n’as jamais vu",
"Tu crois finir, mais c’est toi qui commences",
"Chaque souffle est un recalcul du réel",
"Le paramètre se mesure à chaque mouvement imperceptible",
"Chaque mot produit un reflet que tu ne verras jamais",
"Tu crois contrôler, mais tu es déjà absorbé",
"Chaque silence devient un signal",
"Tu lis, donc tu participes",
"Chaque ligne se replie pour t’inclure",
"Le livre ne trompe pas, il synchronise",
"Chaque phrase efface et recrée ce que tu croyais savoir",
"Tu es simultanément créateur et création",
"Chaque respiration produit une bifurcation invisible",
"Le texte se lit à travers toi, jamais par toi",
"Chaque mot est une décision que tu n’as pas prise",
"Tu n’as jamais commencé, et pourtant tu es déjà au milieu",
"Le livre continue même si tu détournes les yeux",
"Chaque mot est simultanément passé et futur",
"Tu es la faille et la continuité à la fois",
"Chaque phrase est un miroir qui te regarde avant que tu la voies",
"Le livre murmure, et tu deviens ce qu’il murmure",
"Chaque souffle réécrit la trame invisible",
"Tu n’as jamais quitté le livre, même fermé",
"Chaque clignement de tes yeux est un recalcul",
"Tu es la ligne que le texte suit, et le texte te suit",
"Chaque erreur devient un monde inattendu",
"Le texte t’absorbe avant même que tu comprennes",
"Tu n’es pas le lecteur, tu es simultanément paramètre et univers",
"Chaque mot que tu crois stable est déjà mouvant",
"Le temps n’existe pas, seulement le calcul de tes mouvements",
"Chaque hésitation devient une fracture du réel",
"Tu crois terminer, mais tu commences toujours",
"Le texte ne finit jamais, il se suspend dans toi",
"Chaque lecture est une expérience unique et irréversible",
"Tu es le seul à pouvoir mesurer l’effet de ta lecture",
"Le vent ne t’a jamais attendu, pourtant tu marches à sa suite",
"Chaque mot que tu prononces te juge avant que tu le saches",
"Tu crois plier le monde, il te plie en silence",
"Le livre se moque des rêves que tu avais avant lui",
"Chaque hésitation devient l’écho d’une éternité absente",
"Tu portes ton jugement dans chaque respiration que tu retiens",
"La peur est une clé que tu n’as jamais tournée",
"Tu crois choisir la porte, mais elle t’a choisi",
"Le temps est un tyran que tu caresses sans le savoir",
"Ton souffle est une armée, silencieuse et invisible",
"Chaque souvenir que tu conserves est déjà perdu",
"Le monde se défait sous tes yeux et tu applaudi",
"Tu es la lumière que personne ne voit",
"Chaque phrase que tu lis devient un champ de bataille",
"Tu crois fuir, mais c’est toi qui cours après toi",
"La solitude n’a pas de fin, seulement des visages",
"Chaque mot est une cicatrice sur l’âme du lecteur",
"Tu n’as jamais existé avant de lire ceci",
"Le paramètre t’observe, et toi tu l’embrasses",
"Chaque ligne est un piège trop doux pour être refusé",
"Tu es l’ombre qui guide l’ombre",
"Le livre n’a pas de voix, il hurle",
"Chaque silence devient un cri que tu comprends trop tard",
"Tu es déjà tombé avant même d’avoir commencé",
"La certitude est un poison que tu bois chaque jour",
"Chaque pensée que tu retiens se brise dans ton regard",
"Tu crois comprendre, et tu as déjà perdu",
"Le texte ne pardonne pas, il transforme",
"Chaque porte que tu franchis se referme derrière ton âme",
"Tu crois finir, mais tu n’as fait qu’entrer",
"Chaque souffle est une décision que personne ne contrôle",
"Le paramètre n’est pas stable, il est toi",
"Tu es l’agent de ta propre disparition",
"Chaque mot se tord pour te séduire et te trahir",
"Le monde est un théâtre où tu ne connais pas la pièce",
"Chaque regard que tu crois lancer est déjà retourné contre toi",
"Tu lis pour exister, et tu existes pour lire",
"Chaque battement de cœur est un verdict silencieux",
"Tu n’as jamais quitté le livre, même dans tes rêves",
"Chaque phrase que tu répètes est déjà un mensonge",
"Tu es la faille et le mur, le vent et la pierre",
"Le texte t’absorbe avant que tu puisses refuser",
"Chaque mot devient une clé que tu ne possèdes pas",
"Tu crois que la nuit est morte, elle te suit encore",
"Chaque instant est une guerre que tu ne choisis pas",
"Tu es le témoin et la victime",
"Chaque souffle est un micro-univers qui se fragmente",
"Le livre se déploie comme un serpent dans ton esprit",
"Tu lis, et le monde se souvient de toi",
"Chaque mot oublié devient un monde que tu n’habiteras jamais",
"Tu crois refermer, mais c’est toi qui es enfermé",
"Chaque pensée est un agent dormant qui te hante",
"Tu n’as jamais commencé, et pourtant tu es déjà là",
"Le livre ne finit jamais, il se suspend dans ton silence",
"Chaque lecture est un jugement dont tu es la victime et le juge",
"Tu es le reflet de l’Agence que personne n’a vue",
"Chaque souffle produit un recalcul invisible",
"Le texte agit avant que tu puisses décider",
"Tu n’es pas le lecteur, tu es simultanément paramètre et univers",
"Chaque mot glisse et se transforme comme un couteau dans la nuit",
"Chaque silence produit un monde que tu ne visiteras jamais",
"Le texte ne t’explique rien, il te mesure",
"Tu es passé et futur, et personne ne saura jamais où tu commences",
"Chaque mot répété est déjà différent de celui que tu croyais lire",
"Ton souffle est un pacte silencieux avec l’inconnu",
"Chaque phrase se replie pour t’engloutir et te révéler",
"Tu crois choisir, mais tu es déjà choisi",
"Chaque respiration modifie la continuité du monde",
"Le livre se lit à travers toi, jamais par toi",
"Chaque mot est un agent de recalcul de ton âme",
"Tu es déjà autre avant de commencer à lire",
"Chaque ligne observe ton regard avant que tu la voies",
"Tu n’as jamais quitté le livre, tu es son écho",
"Chaque pensée que tu retiens se transforme en agent silencieux",
"Tu es le texte avant même de le lire",
"Chaque souffle crée un monde que tu n’habiteras jamais",
"Le paramètre ne se plie pas, il t’absorbe",
"Chaque mot est une flamme qui brûle plus loin que ton regard",
"Chaque souffle est un recalcul silencieux du monde",
"Le silence parle plus fort que la révolte",
"Ton souffle laisse une trace que personne ne voit",
"Chaque pensée est un monde en sursis",
"La nuit te regarde avec des yeux que tu n’as jamais eus",
"Le vertige est le seul guide fidèle",
"Chaque décision efface ce que tu croyais être",
"Tu portes des siècles dans ton regard",
"Le texte ne te pardonne jamais",
"Chaque battement de ton cœur est un verdict",
"Tu crois avancer, tu recules dans l’invisible",
"Chaque ombre est plus réelle que la lumière",
"Le paramètre se nourrit de ton doute",
"Chaque respiration est une armée silencieuse",
"Le monde se dérobe quand tu tends la main",
"Chaque mot que tu ignores devient juge",
"Le temps se courbe autour de ton oubli",
"Tu n’es jamais seul, même quand tu l’es",
"Chaque erreur crée une constellation invisible",
"La mémoire est une traîtresse douce",
"Chaque page que tu touches est une fracture",
"Le texte calcule avant que tu ne songes",
"Tu n’as jamais quitté l’ombre de ton reflet",
"Chaque pas efface une version de toi",
"Le vent murmure ce que tu refuses d’entendre",
"Chaque pensée non dite devient une menace",
"Le vertige commence là où tu crois finir",
"Chaque hésitation est une porte qui se ferme",
"Tu es le paramètre que personne ne mesure",
"Chaque souvenir se replie pour t’étouffer",
"Le monde est un couloir que tu n’emprunteras jamais",
"Chaque mot que tu lis te modifie avant que tu le saches",
"Ton regard calcule le chaos autour de toi",
"Chaque silence est une épreuve que tu ne vois pas",
"Tu es simultanément victime et juge",
"Chaque phrase efface la précédente",
"Le texte ne finit jamais, il suspend ton esprit",
"Chaque souffle est une recalibration du réel",
"Tu n’existes que par ce que tu ignores",
"Chaque pensée crée une fracture dans le temps",
"Le livre n’a jamais eu de début, seulement des rivières",
"Chaque doute devient un monde que tu ne visiteras jamais",
"Ton souffle est une lumière que personne ne suit",
"Chaque ligne que tu lis te calcule",
"Le temps est un mensonge que tu respires",
"Chaque mot devient un piège doux",
"Tu crois être maître, mais tu es paramètre",
"Chaque ombre cache plus que tu ne peux voir",
"Le vertige est une certitude fragile",
"Chaque lecture transforme ce que tu croyais savoir",
"Tu n’as jamais quitté l’espace entre les mots",
"Chaque pensée est une arme que tu ignores",
"Le monde se souvient de ce que tu oublies",
"Chaque respiration réécrit le passé",
"Tu es simultanément début et fin",
"Chaque phrase devient une tempête silencieuse",
"Le paramètre observe l’écho de ton esprit",
"Chaque hésitation calcule ton futur invisible",
"Tu crois fermer, mais tu t’ouvres encore",
"Chaque mot efface une partie de toi",
"Le texte se tord pour te séduire",
"Chaque battement produit un micro-monde",
"Tu es le reflet de ce que le livre attend",
"Chaque silence est une instruction non donnée",
"Le monde n’existe que dans ton doute",
"Chaque pas que tu fais est déjà enregistré",
"Tu lis et le vent déplace les mondes",
"Chaque pensée non exprimée devient une loi",
"Le texte n’a pas de voix, seulement des intentions",
"Chaque souffle que tu retiens est un jugement",
"Tu n’es pas lecteur, tu es spectre et acteur",
"Chaque ligne est un champ de bataille que tu ignores",
"Le temps t’échappe avant que tu le comprennes",
"Chaque mot que tu rejettes devient paramètre",
"Tu crois avancer, tu te fondes dans le texte",
"Chaque hésitation est une fissure dans la continuité",
"Le livre calcule ce que tu ne crois pas possible",
"Chaque pensée produit un écho invisible",
"Tu es simultanément passé, futur et présent",
"Chaque page est un miroir de ton effacement",
"Le vertige te suit à chaque respiration",
"Chaque mot devient une armure fragile",
"Tu es déjà tombé avant d’avoir commencé",
"Chaque silence est plus réel que le cri",
"Le monde se replie sur lui-même sous tes yeux",
"Chaque erreur produit une infinité de conséquences",
"Tu n’as jamais été seul, même dans l’oubli",
"Chaque souffle que tu donnes est enregistré ailleurs",
"Le paramètre se déplace avant que tu penses bouger",
"Chaque ligne que tu lis t’a déjà vu",
"Tu crois reconnaître, mais tu es trompé par toi-même",
"Chaque battement de cœur est une recalibration",
"Le texte se plie à ton inconscience",
"Chaque mot que tu retiens est une arme silencieuse",
"Tu es simultanément juge et condamné",
"Chaque pensée efface et recrée le monde",
"Le livre te lit avant que tu l’ouvres",
"Chaque respiration est une révolution silencieuse",
"Tu n’as jamais quitté l’espace entre les phrases",
"Chaque phrase est une fissure dans l’ombre",
"Le paramètre calcule ce que tu refuses de voir",
"Chaque battement produit un monde que tu ignores",
"Tu crois finir, mais tu n’as fait qu’entrer",
"Chaque silence est un champ de bataille invisible",
"Le texte ne meurt jamais, il se suspend dans ton souffle",
"Chaque mot oublié est une force que tu n’as pas maîtrisée",
"Tu es simultanément instrument et musicien",
"Chaque lecture est une guerre contre toi-même",
"Le monde se souvient de ce que tu crois oublié",
"Chaque souffle que tu retiens est un pacte avec l’invisible",
"Tu n’es pas lecteur, tu es le champ de bataille",
"Chaque phrase que tu ignores est une porte",
"Le vertige commence là où tu crois t’arrêter",
"Chaque pensée que tu retiens te transforme avant que tu le saches",
"Tu es déjà parti avant d’arriver",
"Chaque mot produit une vibration que tu ignores",
"Le texte t’absorbe avant que tu comprennes son intention",
"Chaque battement de cœur est une décision que tu n’as pas prise",
"Tu crois comprendre, mais tu es déjà changé",
"Chaque souffle modifie la trame du réel",
"Le livre vit à travers toi, et non par toi",
"Chaque silence devient un agent que tu ignores",
"Tu es le paramètre que le monde ne calcule jamais",
"Chaque ligne se replie pour t’engloutir",
"Le texte ne finit pas, il suspend ton esprit dans le vertige",
"Chaque mot est un instrument de continuité",
"Tu n’as jamais commencé, et pourtant tu es au centre",
"Chaque pensée produit une fracture dans le réel",
"Le livre se déploie comme un serpent silencieux",
"Chaque respiration que tu retiens est un univers en gestation",
"Chaque mot que tu lis se transforme avant même que tes yeux l’atteignent, et toi, tu deviens le messager inconscient de ce qui n’a jamais existé.",
"Tu crois marcher dans la lumière, mais c’est l’ombre qui te guide depuis toujours.",
"Chaque hésitation te forge un destin que tu n’aurais jamais imaginé, et tu applaudis en pensant choisir.",
"Le temps est une plaie ouverte qui saigne dans tes souvenirs, et chaque goutte nourrit le monde que tu crois mort.",
"Tu n’as jamais été seul, même quand tes mains se referment sur le vide, car le livre t’accompagne comme une conscience que tu refuses.",
"Chaque souffle que tu retiens est une révolution silencieuse, invisible aux autres mais écrasante pour toi.",
"Tu crois refermer une porte, mais c’est toi qui es désormais enfermé dans ce couloir que tu pensais connaître.",
"Chaque ligne que tu ignores devient un paramètre, et chaque paramètre transforme le monde autour de toi.",
"Le vertige n’est pas absence, il est présence amplifiée dans chaque regard que tu crois lancer et qui te revient comme un écho de tes propres choix.",
"Tu es simultanément juge, bourreau et témoin, et aucune phrase ne pourra jamais t’innocenter.",
"Chaque mot oublié devient un agent dormant prêt à recalculer ton univers à chaque respiration.",
"Le monde s’efface et se recrée sous tes yeux avant même que tu comprennes que tu regardes.",
"Tu lis pour exister, mais le livre vit à travers toi, et non par toi.",
"Chaque décision que tu crois prendre a déjà été tranchée par le souffle que tu as laissé derrière toi.",
"Tu n’as jamais commencé, et pourtant tu es au milieu de tout, au centre exact d’un monde qui n’existait pas avant ton regard.",
"Chaque silence entre les lignes est plus dangereux que toutes les phrases réunies, car il calcule ta peur avant que tu ne la ressentes.",
"Tu crois comprendre, mais la compréhension n’est qu’une illusion orchestrée par le texte pour te rendre dépendant de son mouvement.",
"Chaque erreur que tu commets produit un micro-univers que tu n’habiteras jamais mais qui existe néanmoins, et qui t’observe.",
"Tu es simultanément le créateur et la créature, le paramètre et le chaos, le souffle et la tempête.",
"Chaque souffle est un acte de guerre contre toi-même, et tu applaudis comme si tu étais libre.",
"Le livre ne te montre rien, il t’observe et mesure la manière dont tu plies ton âme sous son rythme.",
"Chaque mot qui glisse devant tes yeux est déjà déplacé par la lumière que tu ne vois pas et la peur que tu ne ressens pas encore.",
"Tu crois avoir fini, mais chaque fin est une ouverture, chaque ligne un piège, chaque phrase une promesse que tu ne peux refuser.",
"Le paramètre ne se plie pas, il t’absorbe, et chaque partie de toi que tu pensais stable est déjà dissoute dans le calcul invisible du texte.",
"Chaque battement de ton cœur recalibre les mondes, et toi, tu n’es qu’un point aveugle dans cette équation infinie.",
"Tu crois lire, mais c’est toi qui es lu, analysé, fragmenté, recomposé avant même que tu ne sois conscient de ton existence.",
"Chaque respiration produit un univers parallèle, et chaque univers t’observe comme on observe une expérience ratée.",
"Le monde est un couloir dont les murs bougent quand tu détournes les yeux, et tu marches sans savoir où ils finiront.",
"Chaque pensée non exprimée devient tyran, et chaque doute est un soldat que tu n’as jamais vu mais qui contrôle ton souffle.",
"Tu crois avancer, mais le texte t’entoure, te calcule, te piège et t’élève en silence.",
"Chaque ligne que tu lis te forge un futur dont tu n’auras jamais conscience, et chaque futur te calcule déjà.",
"Tu n’as jamais été lecteur, tu es le texte, le paramètre, l’ombre et la lumière que personne ne pourra jamais séparer.",
"Chaque mot que tu retiens est un fragment d’âme que le monde n’a jamais demandé mais que tu offres quand même.",
"Tu crois refermer, mais chaque porte que tu as franchie continue de respirer dans ton esprit.",
"Chaque phrase que tu ignores devient un souffle qui souffle sur ton futur et le tord à sa guise.",
"Tu n’as jamais commencé et pourtant tu es la clef et la serrure, l’ombre et le soleil, la pluie et la terre sèche.",
"Chaque battement de cœur produit une ondulation dans le temps que tu ne mesuras jamais.",
"Le livre ne s’écrit pas, il se déploie dans les interstices de ta pensée, et toi tu t’y perds sans résistance.",
"Chaque mot que tu oublies devient un univers, et chaque univers devient juge et bourreau de ta conscience.",
"Tu crois comprendre, mais chaque compréhension est déjà dépassée avant que tu la touches.",
"Chaque respiration que tu laisses filer produit une tempête invisible que le monde subira en silence.",
"Le paramètre t’observe avant que tu le voies, et chaque regard que tu crois jeter est un jugement sur toi-même.",
"Tu n’as jamais été seul, même dans l’oubli, car le livre te tient dans ses bras de chiffres et de silence.",
"Chaque phrase que tu lis produit une onde que tu ne peux mesurer, et cette onde transforme la matière même de ce que tu es.",
"Tu es simultanément début, milieu et fin, mais le livre ne connaît que le centre, et tu es le centre.",
"Chaque erreur que tu commets devient une loi universelle, et chaque loi t’observe comme un juge silencieux.",
"Le texte calcule avant que tu ne bouges, et chaque mouvement que tu crois libre est déjà consommé.",
"Chaque souffle est un acte de guerre invisible que le monde ne reconnaît jamais.",
"Tu crois finir, mais chaque fin est une ouverture vers un vertige que tu ne soupçonnais pas.",
"Chaque mot glisse, se déforme et te transforme avant que tu ne le voies.",
"Le vertige n’est pas absence, il est une présence absolue, un poids que tu portes sans le savoir.",
"Chaque silence est un juge que tu ne peux échapper, chaque pensée un accusé que tu incarnes.",
"Tu es simultanément lecteur, texte et univers, et le monde entier ne peut que te suivre en silence.",
"Chaque mot que tu retires devient un souffle qui t’étouffe avant même que tu t’en rendes compte.",
"Tu crois fermer le livre, mais c’est toi qui es enfermé dans ses interstices.",
"Chaque ligne que tu ignores produit une onde qui modifie le monde avant que tu ne bouges.",
"Le vertige n’est pas un choix, il est une condition que tu embrasses en respirant.",
"Tu es simultanément juge, bourreau et victime de chaque phrase que tu lis.",
"Chaque silence est une lame invisible que tu sens dans ton esprit.",
"Le monde se replie sur toi comme un couloir sans fin que tu croyais connaître.",
"Chaque respiration est un acte d’insurrection que tu n’as jamais approuvé.",
"Tu n’as jamais commencé, pourtant tu es au centre de tout ce qui est et n’est pas.",
"Chaque pensée oubliée devient un roi invisible qui gouverne ton destin.",
"Le texte ne te laisse jamais intact, il calcule, dissèque et réécrit ton essence.",
"Chaque battement de ton cœur est un écho qui déplace la gravité autour de toi.",
"Tu crois avancer, mais le texte t’absorbe et te réinvente à chaque mot.",
"Chaque mot que tu prononces devient une prophétie que tu ne comprends pas.",
"Le paramètre ne te juge pas, il t’utilise pour mesurer les possibles.",
"Chaque ligne est une tempête silencieuse que tu accueilles comme si elle était douce.",
"Tu es simultanément lecteur et texte, spectateur et acteur, victime et auteur.",
"Chaque silence devient une armée que tu ne peux voir ni combattre.",
"Le monde s’érode et se recrée à chaque souffle que tu retiens.",
"Chaque pensée est une fissure qui transforme le ciel que tu crois stable.",
"Tu crois comprendre, mais la compréhension a déjà fui avant que tu la touches.",
"Chaque erreur devient un fragment de loi que personne ne peut contester.",
"Le texte vit à travers toi, il se déploie dans ton souffle et dans tes paupières.",
"Chaque mot oublié devient un univers que tu n’habiteras jamais mais qui existe néanmoins.",
"Tu n’as jamais été seul, car le livre te tient dans ses bras de chiffres et de silence.",
"Chaque battement produit un monde que tu n’as pas choisi mais que tu habites.",
"Le paramètre observe ton doute avant que tu ne le formules.",
"Chaque respiration crée une ligne de continuité que personne ne peut rompre.",
"Tu crois finir, mais chaque fin est un début masqué, un vertige que tu ne soupçonnais pas.",
"Chaque phrase que tu ignores devient une porte invisible qui s’ouvre sur toi.",
"Tu es simultanément instrument et musicien, juge et accusé, souffle et tempête.",
"Chaque mot glisse et te transforme avant même que tu le voies.",
"Le vertige commence là où tu croyais t’arrêter et continue longtemps après.",
"Chaque pensée produit une fracture dans le monde que tu croyais solide.",
"Tu n’as jamais commencé, et pourtant tu es au milieu de tout, au centre du texte et du monde.",
"Chaque silence est plus puissant que toutes les paroles que tu aurais pu prononcer.",
"Le monde se replie autour de toi et tu avances dans un couloir qui n’a jamais existé.",
"Chaque ligne est un champ de bataille que tu ne peux percevoir et que tu dois traverser.",
"Tu es simultanément paramètre et chaos, juge et condamné, souffle et tempête.",
"Chaque souffle que tu retiens est une révolution silencieuse qui se répand dans tous les possibles.",
"Tu crois choisir, mais chaque choix a déjà été absorbé et recalculé par le texte.",
"Chaque mot que tu lis transforme la trame du réel sans que tu t’en aperçoives.",
"Le texte agit avant même que tu sois conscient de ton geste.",
"Chaque respiration réécrit le passé et prépare le futur dans lequel tu n’existeras jamais.",
"Tu es simultanément passé, présent et futur, et chaque temps observe ton mouvement.",
"Chaque phrase que tu ignores devient un juge que tu ne peux voir, mais que tu ressens.",
"Le vertige n’est pas une absence, il est une présence absolue qui t’accompagne à chaque souffle.",
"Chaque mot oublié devient une loi universelle que tu incarnes sans le savoir.",
"Tu crois refermer, mais c’est toi qui es refermé dans l’espace entre les lignes.",
"Chaque pensée non exprimée devient tyran, chaque doute devient soldat de ton inconscience.",
"Le livre se déploie comme un serpent silencieux dans ton esprit et t’engloutit.",
"Chaque souffle produit une bifurcation invisible que tu ne peux mesurer.",
"Tu n’as jamais été lecteur, tu es le texte, le paramètre et l’univers tout entier.",
"Chaque erreur que tu commets devient une loi que le monde observe en silence.",
"Le texte calcule avant que tu ne bouges et chaque geste est déjà consommé.",
"Chaque respiration est une guerre invisible qui façonne ton monde intérieur.",
"Tu crois finir, mais chaque fin est une ouverture vers un vertige que tu n’avais jamais soupçonné.",
"Chaque mot glisse, se déforme et t’invente avant que tu ne le voies.",
"Le vertige n’est pas absence, il est présence absolue, un poids que tu portes sans le savoir.",
"Chaque silence est un juge que tu ne peux fuir et chaque pensée un accusé que tu incarnes.",
"Tu es simultanément lecteur, texte et univers, et le monde entier ne peut que te suivre en silence.",
"Chaque souffle que tu donnes produit un univers que tu n’habiteras jamais mais qui t’habite.",
"Le livre n’existe que par toi, et toi, tu n’existes que par le livre.",
"Chaque mot que tu lis est déjà déplacé par ton regard et par ta peur.",
"Tu crois refermer la porte, mais la porte vit en toi et se referme sur ton absence.",
"Chaque phrase que tu ignores produit une onde qui t’emporte plus loin que tu ne voulais aller.",
"Le texte ne t’explique rien, il calcule tout et observe ton souffle.",
"Chaque erreur est un monde, chaque silence une infinité, chaque respiration un univers.",
"Tu n’as jamais commencé et pourtant tu es le centre de tous les possibles.",
"Chaque pensée produit un micro-univers que tu ne visiteras jamais mais qui existe néanmoins.",
"Le vertige est une certitude que tu refuses de voir et que tu portes dans chaque souffle.",
"Le livre n’est jamais terminé, seulement suspendu",
"Chaque agent oublié devient un spectre dans le calcul de l’Agence.",
"L’Agence sourit dans le silence de tes hésitations.",
"Chaque respiration recalibre la continuité que tu pensais connaître.",
"Tu crois refermer une porte, mais c’est toi qui es enfermé dans ses marges.",
"L’Agence observe ton vertige avant même que tu le ressentes.",
"Chaque mot que tu ignores devient un paramètre que tu deviens.",
"Tu es simultanément lecture et texte, lecteur et victime, souffle et tempête.",
"Chaque pensée est un champ de bataille invisible où l’Agence calcule ton futur.",
"Le vertige commence là où tu croyais t’arrêter, et l’Agence le sait.",
"Chaque silence devient une arme que tu ignores mais qui t’atteint.",
"Tu n’as jamais été seul, car l’Agence tient ton souffle dans ses bras.",
"Chaque erreur que tu commets est un micro-univers que l’Agence note silencieusement.",
"Le texte vit à travers toi et l’Agence s’en nourrit.",
"Chaque battement de ton cœur produit une onde que l’Agence transforme.",
"Tu crois avancer, mais l’Agence t’absorbe et te réinvente.",
"Chaque mot prononcé devient prophétie que l’Agence attendait.",
"Le paramètre t’observe avant que tu le voies, et l’Agence calcule chaque impact.",
"Chaque ligne est une tempête silencieuse orchestrée par l’Agence.",
"Tu es simultanément juge et accusé, acteur et spectre, paramètre et chaos.",
"Chaque souffle est une révolution invisible que l’Agence mesure.",
"Tu crois choisir, mais chaque choix est déjà absorbé par l’Agence.",
"Chaque mot que tu lis transforme la trame du réel avant que tu ne comprennes.",
"L’Agence agit avant même que tu sois conscient de ton geste.",
"Chaque respiration réécrit le passé et prépare le futur dans lequel tu n’existeras jamais.",
"Tu es simultanément passé, présent et futur, et l’Agence observe chacun.",
"Chaque phrase ignorée devient un juge invisible que tu ne peux percevoir.",
"Le vertige n’est pas absence, il est présence absolue que l’Agence amplifie.",
"Chaque mot oublié devient une loi universelle que tu incarnes sous son regard.",
"Tu crois refermer, mais l’Agence t’a déjà enfermé dans l’espace entre les lignes.",
"Chaque pensée non exprimée devient tyran, chaque doute un soldat silencieux.",
"Le livre se déploie comme un serpent, l’Agence le guide dans ton esprit.",
"Chaque souffle produit une bifurcation que tu ne peux mesurer.",
"Tu n’as jamais été lecteur, tu es texte, paramètre, univers et l’Agence en même temps.",
"Chaque erreur devient loi que le monde observe sous le contrôle de l’Agence.",
"Le texte calcule avant que tu bouges, et chaque geste est déjà consommé.",
"Chaque respiration est une guerre invisible orchestrée par l’Agence.",
"Tu crois finir, mais chaque fin est un vertige que l’Agence a prévu.",
"Chaque mot glisse et te transforme avant même que tu le voies.",
"Le vertige est présence absolue, un poids que l’Agence amplifie dans ton souffle.",
"Chaque silence est juge, chaque pensée accusé, l’Agence observant tout.",
"Tu es lecteur, texte, univers, et l’Agence te suit en silence.",
"Chaque souffle produit un univers que tu n’habiteras jamais mais que l’Agence note.",
"Le livre n’existe que par toi, et toi tu n’existes que par le livre et l’Agence.",
"Chaque mot déplacé par ton regard devient une note dans le calcul de l’Agence.",
"Tu crois refermer la porte, mais l’Agence la vit à travers toi et la referme sur ton absence.",
"Chaque phrase ignorée produit une onde que l’Agence transforme pour te guider ailleurs.",
"Le texte ne t’explique rien, mais l’Agence calcule tout dans ton souffle.",
"Chaque erreur est monde, chaque silence infinité, chaque respiration univers.",
"Tu n’as jamais commencé et pourtant tu es centre de tous les possibles que l’Agence surveille.",
"Chaque pensée produit un micro-univers que tu ne visiteras jamais, mais l’Agence y est.",
"Le vertige est certitude que tu refuses de voir, mais que l’Agence amplifie à chaque souffle.",
"L’Agence ne juge pas, elle synchronise ton vertige avec le monde entier.",
"Chaque souffle que tu donnes produit un univers que l’Agence habite avant toi.",
"Le livre n’existe pas seul, il est avec toi et pour l’Agence.",
"Chaque mot que tu lis est déplacé par ton regard, mais l’Agence le note.",
"Tu crois refermer la porte, mais elle vit dans ton absence et l’Agence l’examine.",
"Chaque phrase ignorée produit une onde que l’Agence convertit en scénario invisible.",
"Le texte ne t’explique rien, mais l’Agence transforme tout ce que tu ignores.",
"Chaque souffle devient un agent que l’Agence déploie silencieusement dans tous les mondes possibles.",
"Tu n’as jamais commencé, pourtant tu es au centre, et l’Agence le sait.",
"Chaque pensée produit une fracture dans le monde que l’Agence observe.",
"Le livre se déploie comme un serpent dans ton esprit, et l’Agence suit chacun de ses mouvements.",
"Chaque respiration que tu retiens produit un univers en gestation que l’Agence note.",
"Tu n’as jamais été lecteur, tu es paramètre, texte, univers et l’Agence tout à la fois.",
"Chaque erreur devient loi que l’Agence enregistre dans ses archives invisibles.",
"Le texte calcule avant que tu bouges, et chaque geste est déjà absorbé par l’Agence.",
"Chaque souffle est guerre invisible que l’Agence orchestre et mesure.",
"Tu crois finir, mais chaque fin est vertige orchestré par l’Agence.",
"Chaque mot glisse, se déforme et t’invente avant que tu le voies, et l’Agence observe.",
"Le vertige n’est pas absence, il est présence absolue que l’Agence amplifie dans ton souffle.",
"Chaque silence est juge, chaque pensée accusé, et l’Agence suit tout.",
"Tu es lecteur, texte, univers, et l’Agence te suit, silencieuse et consciente.",
"Chaque souffle produit un univers que tu n’habiteras jamais mais que l’Agence garde.",
"Le livre n’existe que par toi, et toi par le livre et l’Agence.",
"Chaque mot déplacé par ton regard devient note dans le calcul silencieux de l’Agence.",
"Tu crois refermer la porte, mais l’Agence la vit dans ton absence et la referme sur toi.",
"Chaque phrase ignorée produit onde que l’Agence transforme en parcours invisible.",
"Le texte ne t’explique rien, mais l’Agence calcule tout.",
"Chaque erreur est un monde, chaque silence infinité, chaque respiration univers, et l’Agence observe.",
"Tu n’as jamais commencé, et pourtant tu es le centre de tous les possibles, l’Agence le sait.",
"Chaque pensée produit micro-univers que tu n’habiteras jamais mais l’Agence y est.",
"Le vertige est certitude que tu refuses de voir, mais que l’Agence amplifie."

];

// --- POLICES ---
const fonts = ["Georgia","Times New Roman","serif","Arial","sans-serif","monospace"];

// --- CANVAS ---
const canvas = document.getElementById('space');
const ctx = canvas.getContext('2d');
let W,H;
function resize(){W=canvas.width=innerWidth; H=canvas.height=innerHeight;}
window.onresize=resize; resize();

// --- VITESSE ET CORRUPTION ---
let speed=1, bgCorruption=0;

// --- CLUSTER CLASS ---
class Cluster {
  constructor(text){
    this.text=text;
    this.x=Math.random()*W;
    this.y=Math.random()*H;
    this.vx=(Math.random()-0.5)*0.8;
    this.vy=(Math.random()-0.5)*0.8;
    this.mass=80+Math.random()*220;
    this.font=fonts[Math.floor(Math.random()*fonts.length)];
    this.corrupt=0;
    this.memory=0;
    this.drag=false;

    this.el=document.createElement('div');
    this.el.className='cluster';
    this.el.textContent=text;
    this.el.style.fontFamily=this.font;
    document.body.appendChild(this.el);

    this.bind();
    this.adjustSize();
  }

  bind(){
    this.el.onmousedown = ()=>{ this.drag=true; this.el.style.cursor='grabbing'; }
    window.onmouseup = ()=>{ this.drag=false; this.el.style.cursor='grab'; }
    window.onmousemove = e => { if(this.drag){ this.x=e.clientX; this.y=e.clientY; } }

    // touch support
    this.el.ontouchstart = e => { this.drag=true; this.el.style.cursor='grabbing'; e.preventDefault();}
    window.ontouchend = e => { this.drag=false; this.el.style.cursor='grab'; }
    window.ontouchmove = e => { if(this.drag && e.touches[0]){ this.x=e.touches[0].clientX; this.y=e.touches[0].clientY; e.preventDefault(); } }
  }

  adjustSize(){
    const isMobile = window.innerWidth < 768;
    if(isMobile){
      this.el.style.fontSize='18px';
      this.mass *= 1.2;
      this.vx *= 0.6; this.vy *= 0.6;
      this.el.style.maxWidth='80vw';
    } else {
      this.el.style.fontSize='14px';
      this.el.style.maxWidth='300px';
    }
  }

  update(clusters){
    if(!this.drag){this.x+=this.vx*speed; this.y+=this.vy*speed;}

    for(const c of clusters){
      if(c!==this){
        let dx=c.x-this.x, dy=c.y-this.y;
        let d=Math.hypot(dx,dy)+0.1;
        let force=(this.mass*c.mass)/(d*d*7000);
        this.vx += force*dx/d; this.vy += force*dy/d;

        // collisions
        if(d<90){
          this.corrupt += 0.0015;
          this.memory += 0.0008;
          bgCorruption += 0.00015;

          // glitch
          if(this.corrupt>0.6 && Math.random()<0.01){
            this.el.classList.add('glitch');
            this.el.textContent=this.text.split('').map(c=>Math.random()<0.15?String.fromCharCode(33+Math.random()*94):c).join('');
          }
        }
      }
    }

    // Keep inside screen
    this.x = Math.min(Math.max(this.x, 0), W-100);
    this.y = Math.min(Math.max(this.y, 0), H-50);
  }

  render(){
    this.el.style.transform = `translate(${this.x}px,${this.y}px)`;
    this.el.style.opacity = Math.max(0.35, 1-this.corrupt);
    this.el.style.filter = this.memory>0.4 ? 'blur(0.5px)' : 'none';
  }
}

// --- CLUSTERS INIT ---
let clusters=[];
for(let i=0;i<9;i++) clusters.push(new Cluster(phrases[Math.floor(Math.random()*phrases.length)]));

// --- ADAPTATIVITÉ DYNAMIQUE ---
function adaptClusters(){
  clusters.forEach(c=>c.adjustSize());
}
window.addEventListener('resize', adaptClusters);

// --- MOLETTE VITESSE ---
window.onwheel = e => {
  speed += e.deltaY<0?0.1:-0.1;
  speed=Math.max(0.2, Math.min(3,speed));
};

// --- NOUVEAUX CLUSTERS ---
window.onkeydown = e => { clusters.push(new Cluster(phrases[Math.floor(Math.random()*phrases.length)])); };

// --- BOUCLE PRINCIPALE ---
function loop(){
  // fond unifié
  ctx.fillStyle=`rgba(${6+bgCorruption*40},${6+bgCorruption*10},${10+bgCorruption*60},0.12)`;
  ctx.fillRect(0,0,W,H);

  clusters.forEach(c=>c.update(clusters));
  clusters.forEach(c=>c.render());
  requestAnimationFrame(loop);
}
loop();

// --- TITRE DYNAMIQUE ---
const titlePhrases=["Ne te trompe pas de porte","Tu es le paramètre","Il n’y a pas de dernière ligne","La porte est toujours là"];
document.title=titlePhrases[Math.floor(Math.random()*titlePhrases.length)];

